

##############################################################
##### Differential gene expression analysis using DESeq2 #####
##############################################################

## generate the dds object from the raw count matrix

##############################################################
##### LOAD LIBRARIES
##############################################################


library(data.table)
library(tidyverse)
suppressMessages(library(DESeq2))

##############################################################
##### LOAD DATA
##############################################################


## load the raw combined counts data
dt_combined_counts <- fread(
    file = snakemake@input[['combined']]
)


##############################################
### Create DESeq2 inputs 
##############################################


##########
## Sample information data
##########

## extract the colnames that correspond to the sample id (removing the 'gene' names)
sample_id <- colnames(dt_combined_counts)[colnames(dt_combined_counts) != 'gene']

## extract the sample information
sample_information <- lapply(
    X = sample_id,
    function(x) str_split(
        x,
        pattern = '[.]',
    )[[1]]
)

## put the sample information into a data table
sample_information <- cbind(
    data.table('sample_id' = sample_id),
    as.data.table(
        transpose(sample_information)
    )
)

## new colunm names
new_col_names <- c(
    'treat',
    'condition',
    'dai',
    'replicate'
)

## rename column
sample_information <- sample_information [
    ,
    setnames(
        .SD,
        c('V1', 'V2', 'V3', 'V4'),
        new_col_names
    )
]

##########
## Expression data
##########

## Fonction for extract the expression data from the sample contained in the sample information data and put the sample in the same order
generate_deseq2_inputs <- function(
    sample_information_datatable # data table containing the sample_id, treat, condition and dai column names
) {

    ## extract the sample of interest contained in the sample information input
    sample_of_interest <- unlist(sample_information_datatable[, sample_id])

    ## extract expression data of the sample of interest
    dt_combined_counts_subset <- copy(
        dt_combined_counts[, c('gene', sample_of_interest), with = F]
    )

    ## transform the expression data table into data frame
    expression_dataframe <- data.frame(
        dt_combined_counts_subset[,-c('gene'), with = F],
        row.names = dt_combined_counts_subset[, gene]
    )

    ## transform all the values into numeric values
    expression_dataframe <- apply(
        expression_dataframe,
        c(1,2),
        function(x) round(as.numeric(x))
    )

    ## transform the sample information data table input into a data frame
    sample_information_dataframe <- data.frame(
        sample_information_datatable[, -c('sample_id'), with = F],
        row.names = sample_information_datatable[, sample_id]
    )

    ## transform all the values of the sample information to character
    sample_information_dataframe <- apply(
        sample_information_dataframe,
        c(1,2),
        function(x) as.character(x)
    )

    ## transform the character to factors
    sample_information_dataframe <- apply(
        sample_information_dataframe,
        c(2),
        function(x) factor(x)
    )

    sample_information_dataframe[,'treat'] <- factor(sample_information_dataframe[, 'treat'])


    ## put the expression data and the sample information into a list
    output <- list()
    output['count'] <- list(expression_dataframe)
    output['information'] <- list(sample_information_dataframe)

    ## return the list that contain the count and sample information data
    return(output)
}


##############################################################
##### create a dds object 
##############################################################


## function for create a dds object
create_dds_object <- function(
    deseq2_input, # list of inputs generated by the function "generate_deseq2_inputs",
    formula,
    dds_path
) {

    ## create the dds object
    dds <- DESeqDataSetFromMatrix(
            countData = deseq2_input[['count']],
            colData = deseq2_input[['information']],
            design = formula
        )

        ## save the dds object
        saveRDS(
            dds,
            file = dds_path
        )
}


##############################################################
##### Initialize the input of DESeq2
##############################################################


##########
## do I vs C withount taking in account the dai
##########

# extract expression data from the sample information
deseq2_input <- generate_deseq2_inputs(
    sample_information_datatable = sample_information
)

## save the sample information
#fwrite(
#    sample_information,
#    paste(
#        snakemake@output[['DESeq2_dds_init_dir']],
#        '/',
#        'sample_information_condition',
#        '_',
#        'all',
#        '.csv',
#        sep = ''
#    ),
#    sep = ','
#)

fwrite(
    sample_information,
    snakemake@output[['sample_information']],
    sep = ','
)

## create dds object
create_dds_object(
    deseq2_input = deseq2_input,
    formula = formula('~ replicate + dai + condition + treat'),
    dds_path = paste(
        snakemake@output[['DESeq2_dds_init_dir']],
        '/',
        'dds_init_condition',
        '_',
        'all',
        '.dds',
        sep = ''
    )
)


##########
## dot the same but for only infected samples
##########

# extract expression data from the sample information
deseq2_input <- generate_deseq2_inputs(
    sample_information_datatable = sample_information[condition == 'I', !c('condition'), with = F]
)

## create dds object
create_dds_object(
    deseq2_input = deseq2_input,
    formula = formula('~ replicate + treat + dai'),
    dds_path = paste(
        snakemake@output[['DESeq2_dds_init_dir']],
        '/',
        'dds_init_condition',
        '_',
        'all_infected',
        '.dds',
        sep = ''
    )
)

##########
## dot the same but for each dai
##########


## extract the dai value
dai <- (unique(unlist(sample_information[, dai])))

## for each dai, create a dds object
for (i_dai in seq(1, length(dai))) {

    ## extract the dai of interest
    dai_of_interest <- as.numeric(dai[i_dai])

    ## extract the input for deseq2 associated with the dai
    deseq2_input_condition_dai <-  generate_deseq2_inputs(sample_information[dai == dai_of_interest,])


    ## create the dds associated with the dai of interest and save it
    create_dds_object(
        deseq2_input = deseq2_input_condition_dai,
        formula = formula('~ replicate + condition + treat'),
        dds_path = paste(
            snakemake@output[['DESeq2_dds_init_dir']],
            '/',
            'dds_init_condition',
            '_',
            dai[i_dai],
            '.dds',
            sep = ''
        )
    )

    ## save the sample information
    #fwrite(
    #    sample_information[dai == as.character(dai[i_dai]),],
    #    paste(
    #        snakemake@output[['DESeq2_dds_init_dir']],
    #        '/',
    #        'sample_information_condition',
    #        '_',
    #        dai[i_dai],
    #        '.csv',
    #        sep = ''
    #    ),
    #    sep = ','
    #)
}

#Sys.sleep(1000)











