

#################################################
## Generate volcanoplot from the results generated by DESeq2
#################################################


#################################################
## Load the libraries
#################################################

library(data.table)
library(EnhancedVolcano)
library(tidyverse)

#################################################
## Load the data
#################################################

## read the results generated by the DESeq analysis
results <- fread(
    snakemake@input[["results"]]
)

## regex spectific to canola or clubroot
canola_id_prefix_regex <- 'ENSRNA|GSBRNA2T'
clubroot_id_prefix_regex <- 'ENSRNAG|PBRA'

## associate to each gene name, the name of the specie
results[
    grep(
        x = gene_name,
        pattern = canola_id_prefix_regex
    ),
    specie_name := 'canola'
]   
results[
    grep(
        x = gene_name,
        pattern = clubroot_id_prefix_regex
    ),
    specie_name := 'clubroot'
]



#################################################
##  Generate the volcanoplot
#################################################

## thresold used for filtering
pval_threshold <- 0.05
foldchange_threshold <- 2

## associate to each species, a color
results[
    specie_name == 'canola',
    color := 'red3'
]   
results[
    specie_name == 'clubroot',
    color := 'blue3'
]

## attribute grey color for the genes that are not significant
results[
    (abs(log2FoldChange) < foldchange_threshold) | (padj > pval_threshold) ,
    color := 'grey'
]
results[
    (abs(log2FoldChange) < foldchange_threshold) | (padj > pval_threshold) ,
    specie_name := 'ns'
]

## create the vector of color
color_vector <- unlist(results[, color])
names(color_vector) <- unlist(results[, specie_name])

#table(color_vector)
#break
## generate the Volcanoplot
volcano_plot <- EnhancedVolcano(
    toptable = results,
    lab = rownames(results),
    selectLab = c(''),
    x = "log2FoldChange",
    y = "padj",
    colCustom = color_vector,

    title = "",
    pCutoff = pval_threshold,
    FCcutoff = foldchange_threshold,

    colAlpha = 0.50,
    pointSize = 4,
    labSize = 5
) + 
    theme_minimal(base_size = 28) +
    labs(color='Specie') +
    labs(subtitle = 'Volcano Plot')

## save the graph
ggsave(
    snakemake@output[['volcanoplot']],
    plot = volcano_plot,
    device = "png",
    height = 8,
    width = 12
)


#################################################
##  Generate the volcanoplot
#################################################


results <- results[
    !((abs(log2FoldChange) < foldchange_threshold) | (padj > pval_threshold)) ,
]

## retreive the distribution of canola and clubroot genes
gene_distribution <- as.data.table(table(results[,specie_name]))[, setnames(.SD, 'V1', 'specie')]
gene_distribution <- gene_distribution[, percentage := N/sum(N)]
print(gene_distribution)
print(gene_distribution)



## pie chart of the gene distribution
#distribution_bar_chart <- ggplot(
#    data = gene_distribution,
#    aes(x = '', y = percentage, fill = specie)
#) +
#    geom_bar(stat="identity") +
#    theme_minimal(base_size = 28) + 
#    labs(x = '')

#ggsave(
#    'distribution_bar_chart.svg',
#    plot = distribution_pie_chart,
#    device = "svg",
#    height = 8,
#    width = 6
#)



#################################################
## 
#################################################


#################################################
##
#################################################

#################################################
##
#################################################

